- name: Demo on loops
  hosts: all
  tasks:
    - name: print fruit name
      debug:
        msg: fruit name is {{ item }}
      loop:
        - apple
        - banana
        - grape
        - orange
    - name: print fruit name and quantity
      debug:
        msg: fruit name is {{ item.name }}, & Quantity is {{ item.quantity }}
      loop:
        -  { name: "apple", quantity: 100 }
        -  { name: "banana", quantity: 200 }
